In [2]:
import pandas as pd

In [3]:
data = {
    'Produto': ['Camiseta', 'Calça', 'Tênis'],
    'Quantidade': [20, 15, 10],
    'Preço Unitário': [50.0, 70.0, 80.0]
}
df = pd.DataFrame(data)

In [4]:
df

    Produto  Quantidade  Preço Unitário
0  Camiseta          20            50.0
1     Calça          15            70.0
2     Tênis          10            80.0

In [6]:
df['Total'] = df['Quantidade'] * df['Preço Unitário']
df

    Produto  Quantidade  Preço Unitário   Total
0  Camiseta          20            50.0  1000.0
1     Calça          15            70.0  1050.0
2     Tênis          10            80.0   800.0

In [15]:
df_pedidos = pd.read_csv("Pedidos2.csv", sep=";")
df_pedidos

,DataPedido,Regiao,Estado,Vendedor,Item,Unidades,PrecoUnidade
0,7-Jun-2016,Nordeste,Pernambuco,Tobias,Geladeira,62,400.99
1,11-Jul-2016,Nordeste,Paraíba,Nadia,Microondas,29,100.99
2,20-Jul-2016,Sudeste,Minas Gerais,Carlos,Geladeira,55,1200.49
3,19-Jul-2016,Nordeste,Bahia,Tania,Microondas,81,1900.99
4,16-Aug-2016,Sudeste,Rio de Janeiro,Pedro,Geladeira,42,2300.95
5,22-Aug-2016,Nordeste,Alagoas,Tobias,Fogao,35,400.99
6,24-Aug-2016,Sul,Santa Catarina,Mauricio,Lavadora,3,2750.00
7,10-Sep-2016,Sudeste,Minas Gerais,Smith,Lavadora,2,1250.00
8,10-Sep-2016,Sudeste,Rio de Janeiro,Alan,Fogao,7,1000.29
9,12-Sep-2016,Nordeste,Pernambuco,Tobias,Geladeira,16,1500.99
10,26-Sep-2016,Sul,Rio Grande do Sul,Mauricio,Fogao,76,1450.99
11,15-Oct-2016,Sudeste,Minas Gerais,Carlos,Microondas,28,890.99
12,14-Oct-2016,Sul,Rio Grande do Sul,Thomas,Microondas,57,1900.99
13,22-Oct-2016,Nordeste,Sergipe,Tobias,Fogao,64,800.99
14,31-Oct-2016,Sudeste,Rio de Janeiro,Raquel,Fogao,14,1340.29
15,18-Nov-2016,Nordeste,Bahia,Tania,Fogao,15,1900.99
16,17-Nov-2016,Sudeste,Rio de Janeiro,Alex,Microondas,11,1400.99
17,22-Nov-2016,Sudeste,Minas Gerais,Pedro,Geladeira,96,1450.99
18,14-Dec-2016,Sudeste,Rio de Janeiro,Alex,Microondas,94,1900.99
19,12-Dec-2016,Sudeste,Rio de Janeiro,Smith,Fogao,67,1900.29
20,21-Dec-2016,Sudeste,Rio de Janeiro,Raquel,Microondas,28,2400.99
21,29-Dec-2016,Nordeste,Pernambuco,Tania,Geladeira,74,1500.99
22,16-Jan-2017,Nordeste,Ceará,Tobias,Fogao,95,1350.99
23,5-Jan-2017,Sudeste,São Paulo,Alan,Microondas,46,800.99
24,23-Jan-2017,Sudeste,São Paulo,Pedro,Microondas,50,1900.99
25,1-Feb-2017,Sudeste,São Paulo,Smith,Microondas,87,1500.00
26,9-Feb-2017,Sudeste,São Paulo,Alex,Fogao,36,400.99
27,18-Feb-2017,Nordeste,Ceará,Tobias,Microondas,4,1420.99
28,26-Feb-2017,Sudeste,São Paulo,Alan,Fogao,27,1999.99
29,7-Mar-2017,Sul,Paraná,Mauricio,Microondas,7,1900.99
30,15-Mar-2017,Sul,Santa Catarina,Mauricio,Fogao,56,2340.99
31,24-Mar-2017,Sudeste,São Paulo,Alex,Geladeira,50,1433.99
32,1-Apr-2017,Nordeste,Pernanbumco,Tobias,Microondas,60,2400.99
33,10-Apr-2017,Sudeste,São Paulo,Raquel,Fogao,66,1900.99
34,18-Apr-2017,Sudeste,São Paulo,Raquel,Fogao,75,1800.99
35,27-Apr-2017,Nordeste,Bahia,Nadia,Fogao,96,400.99
36,5-May-2017,Sudeste,São Paulo,Alex,Fogao,90,1422.99
37,14-May-2017,Sudeste,São Paulo,Alan,Fogao,53,1340.29
38,22-May-2017,Sul,Rio Grande do Sul,Thomas,Fogao,32,1700.99
39,31-May-2017,Sudeste,São Paulo,Alan,Microondas,80,800.99
40,8-Jun-2017,Nordeste,Rio Grande do Norte,Tobias,Microondas,60,800.99
41,10-Jun-2017,Sudeste,São Paulo,Pedro,Lavadora,5,1250.00
42,11-Jun-2017,Sudeste,São Paulo,Carlos,Fogao,90,400.99

In [16]:
df_pedidos['Total'] = df_pedidos['Unidades'] * df_pedidos['PrecoUnidade']
df_pedidos

,DataPedido,Regiao,Estado,Vendedor,Item,Unidades,PrecoUnidade,Total
0,7-Jun-2016,Nordeste,Pernambuco,Tobias,Geladeira,62,400.99,24861.38
1,11-Jul-2016,Nordeste,Paraíba,Nadia,Microondas,29,100.99,2928.71
2,20-Jul-2016,Sudeste,Minas Gerais,Carlos,Geladeira,55,1200.49,66026.95
3,19-Jul-2016,Nordeste,Bahia,Tania,Microondas,81,1900.99,153980.19
4,16-Aug-2016,Sudeste,Rio de Janeiro,Pedro,Geladeira,42,2300.95,96639.90
5,22-Aug-2016,Nordeste,Alagoas,Tobias,Fogao,35,400.99,14034.65
6,24-Aug-2016,Sul,Santa Catarina,Mauricio,Lavadora,3,2750.00,8250.00
7,10-Sep-2016,Sudeste,Minas Gerais,Smith,Lavadora,2,1250.00,2500.00
8,10-Sep-2016,Sudeste,Rio de Janeiro,Alan,Fogao,7,1000.29,7002.03
9,12-Sep-2016,Nordeste,Pernambuco,Tobias,Geladeira,16,1500.99,24015.84
10,26-Sep-2016,Sul,Rio Grande do Sul,Mauricio,Fogao,76,1450.99,110275.24
11,15-Oct-2016,Sudeste,Minas Gerais,Carlos,Microondas,28,890.99,24947.72
12,14-Oct-2016,Sul,Rio Grande do Sul,Thomas,Microondas,57,1900.99,108356.43
13,22-Oct-2016,Nordeste,Sergipe,Tobias,Fogao,64,800.99,51263.36
14,31-Oct-2016,Sudeste,Rio de Janeiro,Raquel,Fogao,14,1340.29,18764.06
15,18-Nov-2016,Nordeste,Bahia,Tania,Fogao,15,1900.99,28514.85
16,17-Nov-2016,Sudeste,Rio de Janeiro,Alex,Microondas,11,1400.99,15410.89
17,22-Nov-2016,Sudeste,Minas Gerais,Pedro,Geladeira,96,1450.99,139295.04
18,14-Dec-2016,Sudeste,Rio de Janeiro,Alex,Microondas,94,1900.99,178693.06
19,12-Dec-2016,Sudeste,Rio de Janeiro,Smith,Fogao,67,1900.29,127319.43
20,21-Dec-2016,Sudeste,Rio de Janeiro,Raquel,Microondas,28,2400.99,67227.72
21,29-Dec-2016,Nordeste,Pernambuco,Tania,Geladeira,74,1500.99,111073.26
22,16-Jan-2017,Nordeste,Ceará,Tobias,Fogao,95,1350.99,128344.05
23,5-Jan-2017,Sudeste,São Paulo,Alan,Microondas,46,800.99,36845.54
24,23-Jan-2017,Sudeste,São Paulo,Pedro,Microondas,50,1900.99,95049.50
25,1-Feb-2017,Sudeste,São Paulo,Smith,Microondas,87,1500.00,130500.00
26,9-Feb-2017,Sudeste,São Paulo,Alex,Fogao,36,400.99,14435.64
27,18-Feb-2017,Nordeste,Ceará,Tobias,Microondas,4,1420.99,5683.96
28,26-Feb-2017,Sudeste,São Paulo,Alan,Fogao,27,1999.99,53999.73
29,7-Mar-2017,Sul,Paraná,Mauricio,Microondas,7,1900.99,13306.93
30,15-Mar-2017,Sul,Santa Catarina,Mauricio,Fogao,56,2340.99,131095.44
31,24-Mar-2017,Sudeste,São Paulo,Alex,Geladeira,50,1433.99,71699.50
32,1-Apr-2017,Nordeste,Pernanbumco,Tobias,Microondas,60,2400.99,144059.40
33,10-Apr-2017,Sudeste,São Paulo,Raquel,Fogao,66,1900.99,125465.34
34,18-Apr-2017,Sudeste,São Paulo,Raquel,Fogao,75,1800.99,135074.25
35,27-Apr-2017,Nordeste,Bahia,Nadia,Fogao,96,400.99,38495.04
36,5-May-2017,Sudeste,São Paulo,Alex,Fogao,90,1422.99,128069.10
37,14-May-2017,Sudeste,São Paulo,Alan,Fogao,53,1340.29,71035.37
38,22-May-2017,Sul,Rio Grande do Sul,Thomas,Fogao,32,1700.99,54431.68
39,31-May-2017,Sudeste,São Paulo,Alan,Microondas,80,800.99,64079.20
40,8-Jun-2017,Nordeste,Rio Grande do Norte,Tobias,Microondas,60,800.99,48059.40
41,10-Jun-2017,Sudeste,São Paulo,Pedro,Lavadora,5,1250.00,6250.00
42,11-Jun-2017,Sudeste,São Paulo,Carlos,Fogao,90,400.99,36089.10