In [1]:
import pandas as pd

In [5]:
dados = {
    'Nome': ['Alice', 'Bob', 'Charlie'],
    'Idade': [20, 22, 19],
    'Cidade': ['Fortaleza', 'Rio de Janeiro', 'Mossoró']
}

In [6]:
df = pd.DataFrame(dados)

In [7]:
df

      Nome  Idade          Cidade
0    Alice     20       Fortaleza
1      Bob     22  Rio de Janeiro
2  Charlie     19         Mossoró

In [8]:
df.head(1)

    Nome  Idade     Cidade
0  Alice     20  Fortaleza

In [9]:
df.tail(1)

      Nome  Idade   Cidade
2  Charlie     19  Mossoró