In [1]:
import pandas as pd

In [3]:
df = pd.read_json("dados/receitas.json", encoding="utf-8")
df

                                            Receitas
0  {'título': 'Bolo de Chocolate', 'tempo_preparo...
1  {'título': 'Salada Caesar', 'tempo_preparo': '...
2  {'título': 'Pasta ao Pesto', 'tempo_preparo': ...

In [5]:
df_receitas = pd.json_normalize(
    df['Receitas'],
    'ingredientes',
    ['título', 'tempo_preparo', 'porcoes']
)
df_receitas

         ingrediente  quantidade             título tempo_preparo porcoes
0   Farinha de Trigo   2 xícaras  Bolo de Chocolate        45 min       8
0             Açúcar    1 xícara  Bolo de Chocolate        45 min       8
0               Ovos   3 xícaras  Bolo de Chocolate        45 min       8
0              Leite    1 xícara  Bolo de Chocolate        45 min       8
0           Manteiga  1/2 xícara  Bolo de Chocolate        45 min       8
1      Alface Romana    1 cabeça      Salada Caesar    20 minutos       4
1           Croutons    1 xícara      Salada Caesar    20 minutos       4
1    Queijo parmesão  1/2 xícara      Salada Caesar    20 minutos       4
1       Molho caesar  1/4 xícara      Salada Caesar    20 minutos       4
2              Massa        200g     Pasta ao Pesto    30 minutos       2
2  Manjericão fresco  1/2 xícara     Pasta ao Pesto    30 minutos       2
2    Azeite de oliva  1/3 xícara     Pasta ao Pesto    30 minutos       2
2              Nozes  1/4 xícara     Pasta ao Pesto    30 minutos       2
2    Queijo Parmesão  1/4 xícara     Pasta ao Pesto    30 minutos       2

# Análise total de ingredientes por receita:

In [16]:
receitas_expandidas = []
for receita in df['Receitas']:
    total_ingredientes = len(receita['ingredientes'])
    receita_info = {
        'título': receita['título'],
        'tempo_preparo': receita['tempo_preparo'],
        'porcoes': receita['porcoes'],
        'total_ingredientes': total_ingredientes
    }
    receitas_expandidas.append(receita_info)

In [17]:
receitas_expandidas

[{'título': 'Bolo de Chocolate',
  'tempo_preparo': '45 min',
  'porcoes': 8,
  'total_ingredientes': 5},
 {'título': 'Salada Caesar',
  'tempo_preparo': '20 minutos',
  'porcoes': 4,
  'total_ingredientes': 4},
 {'título': 'Pasta ao Pesto',
  'tempo_preparo': '30 minutos',
  'porcoes': 2,
  'total_ingredientes': 5}]

In [18]:
df_expandido = pd.DataFrame(receitas_expandidas)
df_expandido

              título tempo_preparo  porcoes  total_ingredientes
0  Bolo de Chocolate        45 min        8                   5
1      Salada Caesar    20 minutos        4                   4
2     Pasta ao Pesto    30 minutos        2                   5